### ISSUE TITLE
Implement Encoding and Decoding of Objects as Query Parameters

### ISSUE THREAD

**Issue by BRIHMAT-Naoui** [alamenai/rehook#25]
**Description**

Currently, the `useQueryParams` hook in our library only supports handling string values for query parameters. However, there is a need to encode and decode objects or complex data structures as query parameters, especially in scenarios where we need to share or persist complex application states.

**Example**

Let's consider an e-commerce scenario where we want to share product details as a query parameter in the URL. For example:

```javascript
const product = {
  id: 123,
  name: 'Product Name',
  price: 19.99,
  category: 'Electronics',
  tags: ['featured', 'new']
};

// Encode the product object as a query parameter
const encodedProduct = encodeURIComponent(JSON.stringify(product));
const url = `https://example.com/products?product=${encodedProduct}`;

**Comment by alamenai** [comment]
Thank you @BRIHMAT-Naoui for suggesting this feature, let me know if you would work on it.

**Comment by BRIHMAT-Naoui** [comment]
> Thank you @BRIHMAT-Naoui for suggesting this feature, let me know if you would work on it.

yes I work on it

**Comment by alamenai** [comment]
Hi @BRIHMAT-Naoui , I guess you meant to convert and extract properties from  an object  and pass them to url query params, right?

**Comment by alamenai** [comment]
Hi @BRIHMAT-Naoui , I'll work on this feature this week.

**Comment by alamenai** [comment]
Hi @BRIHMAT-Naoui ,

I implemented it like this :

```typescript

    const setEncoded = (obj: { [s: string]: string } | ArrayLike<string>) => {
        const encodedParams = new URLSearchParams()

        for (const [key, value] of Object.entries(obj)) {
            encodedParams.append(key, value)
        }

        const newRelativePathQuery = window.location.pathname + '?' + encodedParams.toString()

        history.push(newRelativePathQuery)
    }
```


## Demo

[a85557dd-4f7e-4cc8-9276-dd8208f15992.webm](https://github.com/alamenai/rehook/assets/20143684/29bdc51d-5e8b-4cdd-82a7-85789e82b466)
